site_name: TsDD Docs (v0.1.1)
site_url: https://m-zakeri.github.io
repo_url: https://github.com/m-zakeri/TsDD
site_description: Testability-driven development
site_author: Morteza Zakeri
copyright: © 2020-2022 TsDD project - Reverse engineering laboratory

theme:
  name: material
  palette:
    scheme: preference
    primary: blue
  icon:
    logo: material/library
  features:
    - header.autohide
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/mortazazakeri/


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Publications: publications.md
    - Benchmarks: benchmarks.md
    - Datasets: datasets.md
    - Modules:
        - Main: modules/main.md
    - Related projects: related_projects.md
    - Issue Tracker: 'https://github.com/m-zakeri/TsDD/issues'